#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'erlang',        :git => 'git://github.com/relaynetwork/erlang.git'
cookbook 'nginx',         :git => 'git://github.com/opscode-cookbooks/nginx.git'
cookbook 'sysctl',        :git => 'https://github.com/onehealth-cookbooks/sysctl.git'

cookbook 'rvm',           :git => 'https://github.com/kyleburton/chef-rvm.git'
cookbook 'ejabberd',      :git => 'git@github.com:kyleburton/chef-cookbooks.git',      :path => 'ejabberd'
cookbook 'bash_profile',  :git => 'git@github.com:kyleburton/chef-cookbooks.git',      :path => 'bash_profile'
cookbook 'limits',        :git => 'git@github.com:kyleburton/chef-cookbooks.git',      :path => 'limits'
cookbook 'packages',      :git => 'git@github.com:kyleburton/chef-cookbooks.git',      :path => 'packages'
