# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'rubygems'
require 'bundler'
Bundler.require
require 'multi_json'

#def chef_solo config, 

Vagrant::Config.run do |all_config|

  [:ejabberd01, :ejabberd02].each do |node_name|
    all_config.vm.define node_name do |config|
      config.vm.box = "precise64"
      vagrant_json = MultiJson.load(Pathname(__FILE__).dirname.join('nodes', 'ejabberd.json').read)

      config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = ["site-cookbooks", "cookbooks"]
        chef.roles_path = "roles"
        chef.data_bags_path = "data_bags"
        chef.provisioning_path = "/tmp/vagrant-chef"
        chef.json = vagrant_json
        vagrant_json['run_list'].each do |recipe|
          chef.add_recipe(recipe)
        end if vagrant_json['run_list']
      end
    end

  end
end
