# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'rubygems'
require 'bundler'
Bundler.require
require 'multi_json'

#def chef_solo config, 

Vagrant::Config.run do |all_config|


  [{:name => :ejabberd01,
    :ip   => '10.1.0.10'},
   {:name => :ejabberd02,
    :ip   => '10.1.0.11'} ].each do |node_config|
    node_name = node_config[:name]
    all_config.vm.define node_name do |config|
      config.vm.box = "precise64"
      config.vm.network :hostonly, node_config[:ip], :netmask => "255.255.0.0"
      vagrant_json = MultiJson.load(Pathname(__FILE__).dirname.join('nodes', 'ejabberd.json').read)

      config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = ["site-cookbooks", "cookbooks"]
        chef.roles_path = "roles"
        chef.data_bags_path = "data_bags"
        chef.provisioning_path = "/tmp/vagrant-chef"
        chef.json = vagrant_json
        vagrant_json['run_list'].each do |recipe|
          chef.add_recipe(recipe)
        end if vagrant_json['run_list']
      end
    end

  end
end

