# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'rubygems'
require 'bundler'
Bundler.require
require 'multi_json'

#def chef_solo config, 

Vagrant::Config.run do |all_config|


  # NB: if you're changing this list here, you will also need to edit the
  # site-cookbooks/local-jabber-cluster recipe
  [{:name  => :ejabberd01,
    :ip    => '10.1.0.10',
    :ports => {5222 => 6222,
               5223 => 6223}},

   {:name  => :ejabberd02,
    :ip    => '10.1.0.11',
    :ports => {5222 => 7222,
               5223 => 7223}} 
  ].each do |node_config|
    node_name = node_config[:name]
    all_config.vm.define node_name do |config|
      config.vm.box = "precise64"
      config.vm.network :hostonly, node_config[:ip], :netmask => "255.255.0.0"
      vagrant_json = MultiJson.load(Pathname(__FILE__).dirname.join('nodes', 'ejabberd.json').read)

      config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = ["site-cookbooks", "cookbooks"]
        chef.roles_path = "roles"
        chef.data_bags_path = "data_bags"
        chef.provisioning_path = "/tmp/vagrant-chef"
        chef.json = vagrant_json
        vagrant_json['run_list'].each do |recipe|
          chef.add_recipe(recipe)
        end if vagrant_json['run_list']
      end

      (node_config[:ports] || []).each do |vm_port, host_port|
        config.vm.forward_port vm_port, host_port
      end

    end

  end
end

